-- ============================================================
--  ChefChefChef — données de départ (import Notion + exemples)
--  À coller dans l’éditeur SQL de Supabase APRÈS schema.sql.
--  Relançable sans doublons (on conflict do nothing).
-- ============================================================

insert into public.recipes (id, title, servings, prep_min, cook_min, tags, ingredients, steps, notes, source_url, source_text, photo_url, ambiguous, created_by, created_at, updated_at) values
  ('8096f572-19ac-50b8-a8ac-f6892523446b', 'Raclette', 1, null, null, array['fromage','charcuterie','hiver']::text[], array['{"qty":250,"unit":"g","name":"fromage à raclette","note":null}'::jsonb,'{"qty":200,"unit":"g","name":"charcuterie","note":"200 à 250 g · à revoir si jambon en chiffonnade"}'::jsonb]::text[], '{}'::text[], 'Quantités par personne : ajuste le nombre de convives sur la fiche.', null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('83fd94b3-c8ef-5e9a-adaa-cc1a140acc4b', 'Poulet enoki', 2, null, null, array['poulet','champignons','asiatique','wok']::text[], array['{"qty":2,"unit":null,"name":"hauts de cuisses de poulet","note":null}'::jsonb,'{"qty":6,"unit":"gousse","name":"ail","note":"finement hachées"}'::jsonb,'{"qty":3,"unit":"tranche","name":"gingembre","note":"finement hachées"}'::jsonb,'{"qty":400,"unit":"g","name":"champignons enoki","note":"après avoir coupé les racines"}'::jsonb,'{"qty":2,"unit":"c. à soupe","name":"huile","note":null}'::jsonb,'{"qty":1,"unit":"c. à soupe","name":"sauce soja claire","note":null}'::jsonb,'{"qty":0.25,"unit":"c. à café","name":"sucre","note":null}'::jsonb,'{"qty":1,"unit":"c. à café","name":"maïzena","note":null}'::jsonb,'{"qty":150,"unit":"ml","name":"eau","note":null}'::jsonb,'{"qty":3,"unit":"branche","name":"ciboulette chinoise","note":"3 à 4 branches"}'::jsonb]::text[], array['Préparation des enokis : coupez la base des enokis pour séparer les champignons. Rincez-les délicatement si nécessaire.','Préparation du poulet : désossez les hauts de cuisses, retirez la peau et coupez le poulet en petits morceaux.','Sauter le poulet : faites chauffer l''huile dans un wok ou une poêle profonde sur feu vif. Ajoutez le poulet et faites-le revenir en remuant régulièrement.','Ajouter l''ail et le gingembre : incorporez l''ail et le gingembre hachés au poulet. Faites revenir jusqu''à ce qu''ils commencent à dorer.','Ajouter les enokis : ajoutez les enokis dans la poêle. Faites-les sauter pendant 3 à 4 minutes jusqu''à ce qu''ils deviennent tendres.','Préparer la sauce : mélangez la maïzena avec l''eau pour éviter les grumeaux. Versez ce mélange dans la poêle, puis ajoutez la sauce soja et le sucre. Remuez bien pour que la sauce épaississe légèrement.','Ajouter la ciboulette : coupez la ciboulette chinoise en petits morceaux et ajoutez-la à la préparation. Mélangez bien.','Servir : servez immédiatement, accompagné de riz si désiré.']::text[], null, 'https://lacuisinedebernard.com/les-enokis-sautes-lail-et-au-poule/', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('a44de1bf-5d9c-5d35-ab2d-8587bf1d6318', 'Aubergines gratinées express', 1, null, null, array['aubergine','gratin','rapide','végétarien']::text[], array['{"qty":2,"unit":null,"name":"aubergines","note":"env. 550 g"}'::jsonb,'{"qty":null,"unit":null,"name":"huile d''olive","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"origan","note":"ou thym"}'::jsonb,'{"qty":null,"unit":null,"name":"sel","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"poivre","note":null}'::jsonb,'{"qty":400,"unit":"g","name":"emmental râpé","note":null}'::jsonb]::text[], array['Couper les aubergines en belles et longues tranches d''environ 5 mm d''épaisseur.','Préchauffer le four à 190 °C.','Poser les tranches sur une ou 2 plaques de cuisson recouvertes de papier cuisson.','Verser un filet d''huile d''olive par-dessus. Puis saupoudrer d''origan (ou de thym), de sel et de poivre. Répartir l''emmental râpé par-dessus.','Enfourner 15 à 20 min. L''emmental doit commencer à dorer.','Déguster immédiatement.']::text[], null, null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('859fa127-9040-5f07-a821-f4554498a7e2', 'Tzatziki', 6, null, null, array['sauce','grec','concombre','sans cuisson']::text[], array['{"qty":2,"unit":null,"name":"concombres","note":"gros (ou 3 petits)"}'::jsonb,'{"qty":2,"unit":null,"name":"yaourts grecs","note":"soit 400 g de yaourt"}'::jsonb,'{"qty":1,"unit":"c. à soupe","name":"huile d''olive","note":null}'::jsonb,'{"qty":1,"unit":"c. à soupe","name":"feuilles de menthe hachées","note":"on peut mettre aussi de l''aneth ou ne pas mettre d''herbes du tout"}'::jsonb,'{"qty":4,"unit":"gousse","name":"ail","note":null}'::jsonb,'{"qty":1,"unit":"pincée","name":"sel","note":null}'::jsonb,'{"qty":1,"unit":"pincée","name":"poivre","note":null}'::jsonb]::text[], array['Épluchez les concombres. Fendez-les en deux et à l''aide d''une petite cuillère, ôtez-en les graines puis râpez-les (grille fine). Mettez-les dans une passoire et appuyez avec vos mains pour les essorer un maximum. Réservez.','Épluchez les gousses d''ail et pressez-les. Lavez, séchez et hachez la menthe.','Dans un saladier, mettez les filaments de concombre égouttés, les yaourts, la menthe, l''ail, ajoutez une cuillère à soupe d''huile d''olive et assaisonnez avec le sel et le poivre. Mélangez et réservez au réfrigérateur jusqu''au moment de servir.']::text[], null, null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('249b192c-9799-5c96-a059-2742ae36aa0f', 'Taboulé libanais', 4, null, null, array['salade','libanais','sans cuisson','été']::text[], array['{"qty":200,"unit":"g","name":"tomates","note":null}'::jsonb,'{"qty":40,"unit":"g","name":"boulgour","note":null}'::jsonb,'{"qty":1,"unit":null,"name":"oignon nouveau","note":null}'::jsonb,'{"qty":1.5,"unit":"bouquet","name":"persil plat","note":null}'::jsonb,'{"qty":0.5,"unit":"bouquet","name":"menthe","note":null}'::jsonb,'{"qty":1.5,"unit":null,"name":"citron","note":"pressé"}'::jsonb,'{"qty":4,"unit":"c. à soupe","name":"huile d''olive","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"sel","note":null}'::jsonb]::text[], array['Rincez le boulgour, égouttez-le. Transférez-le dans un saladier, ajoutez le jus de citron, l''huile d''olive et laissez-le gonfler 15 minutes.','Coupez le bas des tiges de persil qui ne comportent pas de feuilles, on ne les utilise pas. Émincez très finement le persil au couteau. Hachez très finement les feuilles de menthe. Coupez les tomates en petits dés.','Mélangez le persil, la menthe, les dés de tomates et l''oignon émincé avec le boulgour, salez et servez sans attendre.']::text[], null, 'https://kuri.app/lNdRtmLc2Qb', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('f8eae9ef-46ec-5fe7-ab26-047497e0721e', 'Feuille d''huître', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un lien (article sur la plante « huître potagère »), pas de recette.', 'https://www.rustica.fr/choux-et-legumes-feuilles/l-huitre-potagere-mertensia-maritima,19238.html', 'Feuille d''huitre
https://www.rustica.fr/choux-et-legumes-feuilles/l-huitre-potagere-mertensia-maritima,19238.html', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('81a67763-1fe1-5389-a896-a684d82e91a5', 'Sauce chien', null, null, null, array['sauce','piment']::text[], array['{"qty":2,"unit":"branche","name":"jeunes pousses d''oignons","note":null}'::jsonb,'{"qty":2,"unit":"branche","name":"persil","note":null}'::jsonb,'{"qty":1,"unit":null,"name":"oignon","note":null}'::jsonb,'{"qty":2,"unit":"gousse","name":"ail","note":null}'::jsonb,'{"qty":0.5,"unit":null,"name":"piment fort","note":"ou 2 piments végétariens"}'::jsonb,'{"qty":3,"unit":"c. à soupe","name":"huile","note":null}'::jsonb,'{"qty":1,"unit":"c. à café","name":"sel","note":null}'::jsonb,'{"qty":0.5,"unit":null,"name":"tomate","note":"émincée"}'::jsonb,'{"qty":150,"unit":"ml","name":"eau bouillante","note":null}'::jsonb]::text[], array['Émincez et mélangez tous les ingrédients sauf l''eau.','Rajouter l''eau bouillante et mélanger pendant 2 min puis laisser reposer au moins 5 min avant de mettre au frigo.']::text[], null, null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('c9cfdfba-b548-5ee9-a683-115fb1eab227', 'Khimo malgache', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un lien, pas de contenu.', 'https://voyage-madagascar.org/khimo/', 'Khimo Malgache
https://voyage-madagascar.org/khimo/', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('369cec07-a884-57de-a87e-128ceb2157f2', 'Nuoc mam', null, null, null, array['sauce','sans cuisson']::text[], array['{"qty":1,"unit":"volume","name":"nuoc pure","note":null}'::jsonb,'{"qty":3,"unit":"volume","name":"eau","note":null}'::jsonb,'{"qty":0.5,"unit":"volume","name":"vinaigre","note":"vin / cidre / riz"}'::jsonb,'{"qty":0.5,"unit":"volume","name":"sucre en poudre","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"ail","note":"en tout petits morceaux"}'::jsonb,'{"qty":null,"unit":null,"name":"piment","note":"optionnel"}'::jsonb,'{"qty":null,"unit":null,"name":"carotte râpée","note":"optionnel"}'::jsonb]::text[], '{}'::text[], null, null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('a55c3565-3bbb-5969-a824-cd0ea9c66150', 'Tiam tiam', null, null, null, array['porc','asiatique','four']::text[], array['{"qty":null,"unit":null,"name":"échine de porc","note":"1/3, coupée en fine lamelle (largeur 1 petit doigt)"}'::jsonb,'{"qty":null,"unit":null,"name":"poitrine de porc","note":"2/3, coupée en fine lamelle (largeur 1 petit doigt)"}'::jsonb,'{"qty":null,"unit":null,"name":"ail","note":"beaucoup"}'::jsonb,'{"qty":null,"unit":null,"name":"sauce hoisin","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"citronnelle","note":"en poudre ou coupée en fine lamelle"}'::jsonb,'{"qty":null,"unit":null,"name":"épices 5 parfums","note":"poivre de Sichuan, fenouil, badiane, cannelle, clou de girofle"}'::jsonb,'{"qty":null,"unit":null,"name":"sauce soja","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"vermicelles de riz","note":"cuites puis rincées plusieurs fois à l''eau froide pour pas qu''elles collent"}'::jsonb,'{"qty":null,"unit":null,"name":"salade à très grandes feuilles","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"concombre","note":"en tranches"}'::jsonb,'{"qty":null,"unit":null,"name":"oignon rouge","note":"en fines tranches"}'::jsonb,'{"qty":null,"unit":null,"name":"ail","note":"coupé en fines tranches, pour l''accompagnement"}'::jsonb,'{"qty":null,"unit":null,"name":"basilic thaï","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"menthe","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"coriandre","note":null}'::jsonb]::text[], array['Viande — mélanger : 1/3 échine de porc et 2/3 poitrine de porc coupées en fine lamelle (largeur 1 petit doigt), beaucoup d''ail, sauce hoisin, citronnelle en poudre ou coupée en fine lamelle, épices 5 parfums (poivre de Sichuan, fenouil, badiane, cannelle, clou de girofle), sauce soja.','Cuire au four à 180 en remuant régulièrement jusqu''à ce que la viande soit bien grillée sur le dessus.','À côté : vermicelles de riz (cuites puis rincées plusieurs fois à l''eau froide pour pas qu''elles collent), salade à très grandes feuilles, concombre en tranches, oignon rouge en fines tranches, ail coupé en fines tranches, basilic thaï, menthe, coriandre.']::text[], null, null, null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('146d6766-2ea4-5c3e-aa2a-d368ad1745f7', 'Soupe chinoise au poulet', 4, null, null, array['soupe','poulet','asiatique','robot']::text[], array['{"qty":320,"unit":"g","name":"filets de poulet","note":null}'::jsonb,'{"qty":1,"unit":"cm","name":"racine de gingembre","note":null}'::jsonb,'{"qty":200,"unit":"g","name":"carottes","note":null}'::jsonb,'{"qty":200,"unit":"g","name":"poireau","note":null}'::jsonb,'{"qty":110,"unit":"g","name":"oignon","note":null}'::jsonb,'{"qty":3,"unit":"g","name":"gousse d''ail","note":null}'::jsonb,'{"qty":2,"unit":"feuille","name":"combava séché","note":"facultatif"}'::jsonb,'{"qty":100,"unit":"g","name":"vermicelles de soja","note":null}'::jsonb,'{"qty":40,"unit":"g","name":"bouillon de poule","note":null}'::jsonb,'{"qty":150,"unit":"cl","name":"eau","note":null}'::jsonb,'{"qty":5,"unit":"cl","name":"sauce soja","note":null}'::jsonb,'{"qty":150,"unit":"g","name":"champignons de Paris","note":null}'::jsonb,'{"qty":1,"unit":"cl","name":"huile","note":null}'::jsonb,'{"qty":20,"unit":"g","name":"pousses de soja","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"basilic thaï","note":"quelques feuilles"}'::jsonb]::text[], array['Dans le bol du robot muni du couteau hachoir Ultrablade, mettez l''ail et l''oignon épluchés et coupés en morceaux. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ».','Remplacez le couteau hachoir Ultrablade par le mélangeur. Ajoutez l''huile, les carottes et le poireau émincés finement. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ». (5 min à 130°)','Pelez et hachez le gingembre. Ajoutez-le dans le bol du robot.','Ajoutez l''eau, le bouillon, les feuilles de combava et le poulet coupé en petits morceaux.','Versez la sauce soja. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ». (15 min à 95°)','Ajoutez les vermicelles et les champignons émincés. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ». (5 min à 130°)','Ajoutez les pousses de soja et le basilic ciselé et servez.']::text[], 'Étapes écrites pour le robot cuiseur (couteau Ultrablade / mélangeur).', 'https://moulinexfood.page.link/51wsdFUJHGuM8tgC8', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('f6da54f3-6c86-5708-a599-df00598f521d', 'Mijoté de poulet au chorizo', 4, null, null, array['poulet','chorizo','mijoté','robot']::text[], array['{"qty":100,"unit":"g","name":"oignon","note":null}'::jsonb,'{"qty":3,"unit":"g","name":"gousse d''ail","note":null}'::jsonb,'{"qty":200,"unit":"g","name":"filets de poulet","note":null}'::jsonb,'{"qty":100,"unit":"g","name":"chorizo","note":null}'::jsonb,'{"qty":100,"unit":"g","name":"poivron rouge","note":null}'::jsonb,'{"qty":2,"unit":"branche","name":"thym","note":null}'::jsonb,'{"qty":10,"unit":"cl","name":"vin blanc","note":null}'::jsonb,'{"qty":400,"unit":"g","name":"tomates cerises","note":"entières"}'::jsonb,'{"qty":2,"unit":"c. à café","name":"sucre","note":null}'::jsonb,'{"qty":2,"unit":"cl","name":"huile d''olive","note":null}'::jsonb,'{"qty":2,"unit":"brin","name":"persil","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"sel","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"poivre","note":null}'::jsonb]::text[], array['Dans le bol du robot muni du couteau hachoir Ultrablade, mettez l''oignon et l''ail pelés. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ».','Remplacez le couteau hachoir Ultrablade par le mélangeur. Ajoutez le poulet, le chorizo coupé en rondelles et l''huile d''olive. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ». (5 min à 130°)','Ajoutez le poivron rouge émincé en lanières, le thym, le persil, le vin blanc, les tomates cerises coupées en deux et le sucre.','Salez et poivrez. Verrouillez le couvercle avec le bouchon et appuyez sur « Start ». (20 min à 95°)','Servez chaud.']::text[], 'Étapes écrites pour le robot cuiseur (couteau Ultrablade / mélangeur).', 'https://moulinexfood.page.link/yZgJdrBfwQuL3XGL6', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('c3c5c69e-2d3a-565d-ac7b-42b7467454dc', 'Pâtes au poulet & tomates cerises', 4, null, null, array['pâtes','poulet','tomate']::text[], array['{"qty":400,"unit":"g","name":"spaghetti","note":null}'::jsonb,'{"qty":400,"unit":"g","name":"tomates cerises","note":null}'::jsonb,'{"qty":4,"unit":null,"name":"escalopes de poulet","note":null}'::jsonb,'{"qty":8,"unit":"c. à soupe","name":"parmesan râpé","note":null}'::jsonb,'{"qty":2,"unit":"gousse","name":"ail","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"basilic","note":null}'::jsonb]::text[], array['Épluchez puis hachez l''ail finement.','Ciselez finement le basilic.','Dans une casserole d''eau bouillante salée, faites cuire les pâtes selon les indications du paquet. En fin de cuisson, prélevez l''équivalent d''une petite louche d''eau de cuisson par personne, puis égouttez les pâtes.','Pendant ce temps, faites chauffer un filet d''huile d''olive dans une poêle et ajoutez-y le poulet. Salez, poivrez et laissez cuire 4 à 5 minutes sur chaque face. Réservez.','Dans la même poêle, ajoutez un filet d''huile d''olive et faites revenir l''ail émincé 2 minutes, à feu doux.','Lavez les tomates cerises et ajoutez-les dans la poêle. Faites-les revenir 2 à 3 minutes. Salez et poivrez.','Versez l''eau de cuisson des pâtes dans la poêle, puis ajoutez-y les pâtes et le parmesan. Mélangez et laissez cuire 2 à 3 minutes supplémentaires.','Ajoutez le basilic, mélangez, puis enlevez la poêle du feu.','Coupez le poulet en tranches et servez-le dans les pâtes. C''est prêt.']::text[], 'Conseils : attention à l''assaisonnement, ça peut être un peu fade (ex : rajouter du concentré de tomate ou des épices).', 'https://app.jow.com/EC0U?action=recipe&recipeId=64c3c646455c560eea66f559&source=jow', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('0d02e482-57b9-54d9-afc1-966e7f2b754c', 'Spaghetti alle vongole', 4, null, null, array['pâtes','fruits de mer','italien']::text[], array['{"qty":400,"unit":"g","name":"spaghetti","note":null}'::jsonb,'{"qty":2,"unit":"kg","name":"palourdes","note":null}'::jsonb,'{"qty":4,"unit":"gousse","name":"ail","note":null}'::jsonb,'{"qty":0.5,"unit":null,"name":"piment oiseau","note":null}'::jsonb,'{"qty":5,"unit":"c. à soupe","name":"huile d''olive","note":null}'::jsonb,'{"qty":0.5,"unit":"verre","name":"vin blanc sec","note":null}'::jsonb,'{"qty":0.5,"unit":"bouquet","name":"persil plat","note":null}'::jsonb,'{"qty":1,"unit":"pincée","name":"sel","note":"ou sel fin"}'::jsonb,'{"qty":1,"unit":"pincée","name":"poivre","note":null}'::jsonb]::text[], array['Rincez les palourdes avec beaucoup d''eau, puis mettez-les dans un saladier. Ajoutez une demi-cuillère à café de gros sel et couvrez d''eau froide. Renouvelez l''opération trois fois, jusqu''à ce qu''il n''y ait plus de résidus dans les palourdes. Rincez-les de nouveau, égouttez-les. Hachez très finement le persil avec 2 gousses d''ail, réservez dans un bol.','Dans une grande poêle creuse, faites revenir l''ail restant avec le piment oiseau, et une petite cuillerée de persil et d''ail hachés. Ajoutez les palourdes, mouillez avec le vin blanc, couvrez et laissez cuire environ 10 minutes en remuant de temps en temps, jusqu''à ce que toutes les palourdes s''ouvrent.','Une fois cuites, retirez les palourdes et filtrez leur jus de cuisson. Remettez le jus dans la poêle, faites-le cuire 5 minutes, à ce qu''il réduise d''un tiers. Gardez-le ensuite dans la poêle sur feu éteint. Pendant ce temps, ôtez la coque de la moitié des palourdes et gardez-en la moitié restante avec leur coque. Gardez toutes les palourdes (avec et sans coque) dans un saladier couvert.','En parallèle, portez à ébullition un grand volume d''eau dans une casserole haute. Dès l''ébullition salez l''eau, puis versez-y les spaghetti. Mélangez-les rapidement avec une cuillère en bois, puis laissez-les cuire pendant le temps indiqué sur le paquet (généralement les spaghetti cuisent en 9 minutes). Dès que les spaghetti sont cuits, égouttez-les « al dente » dans une passoire et versez-les dans la poêle avec le jus de cuisson des palourdes.','Remuez sur feu doux, à ce que les spaghetti s''imbibent de jus de cuisson des palourdes, ajoutez toutes les palourdes et le restant d''ail et persil hachés. Mélangez le tout quelques secondes encore à feu doux, ajoutez un tour de poivre du moulin, un filet d''huile d''olive et servez aussitôt.']::text[], null, 'https://www.750g.com/spaghetti-alle-vongole-pates-aux-palourdes-r205997.htm', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('bfe0ac94-d522-5903-a21c-c9fc7dcbcd30', 'Quiche poivrons & chorizo', 6, null, null, array['quiche','chorizo','four']::text[], array['{"qty":300,"unit":"g","name":"poivrons","note":null}'::jsonb,'{"qty":100,"unit":"g","name":"chorizo","note":null}'::jsonb,'{"qty":3,"unit":null,"name":"œufs","note":null}'::jsonb,'{"qty":100,"unit":"ml","name":"lait","note":null}'::jsonb,'{"qty":100,"unit":"ml","name":"crème liquide","note":null}'::jsonb,'{"qty":100,"unit":"g","name":"tomme","note":null}'::jsonb,'{"qty":1,"unit":null,"name":"pâte brisée","note":null}'::jsonb]::text[], array['Préchauffez le four à 180 °C. Placez la pâte dans votre moule à tarte (le nôtre fait 31 cm de diamètre) et piquez-la à l''aide d''une fourchette. Une fois le four chaud, faites pré-cuire votre pâte pendant 5 minutes.','Pendant ce temps, coupez les poivrons et le chorizo très finement. Râpez la tomme.','Dans un récipient, ajoutez : les œufs, le lait, la crème, la tomme râpée, sel, poivre et fouettez le tout énergiquement.','Une fois la pâte pré-cuite, sortez-la du four, répartissez les poivrons dans le fond avec le chorizo, puis versez l''appareil à quiche par-dessus.','Enfournez votre quiche pendant 45 minutes à 180 °C. Laissez reposer 10 minutes avant de déguster, c''est prêt ! À accompagner d''une salade verte.']::text[], 'Conseils : possibilité de précuire le mélange chorizo/poivron pour que ce soit moins gras, mais dans ce cas ne cuire la quiche que 25 min.', 'https://app.jow.com/EC0U?action=recipe&recipeId=5eda574f67aaed038d640e54&source=jow', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('6f437174-99f3-58f3-a361-400236eab4c3', 'Salade fenouil orange radis', null, null, null, array['salade','à compléter']::text[], '{}'::text[], '{}'::text[], 'Titre du lien : « Sicilian winter salad ».
Import Notion — ambigu : Seulement un lien (Jow), pas de contenu.', 'https://app.jow.com/EC0U?action=recipe&recipeId=5bfbd649dbb15c29fea3f45f&source=jow', 'Salade fenouil orange radis
Sicilian winter salad : https://app.jow.com/EC0U?action=recipe&recipeId=5bfbd649dbb15c29fea3f45f&source=jow', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('82a266db-2862-5951-ad64-e6e82368902e', 'Salade lentilles feta', null, null, null, array['salade','à compléter']::text[], '{}'::text[], '{}'::text[], 'Titre du lien : « Italian lentil salad ».
Import Notion — ambigu : Seulement un lien (Jow), pas de contenu.', 'https://app.jow.com/EC0U?action=recipe&recipeId=5ede1926e86756246cded5f3&source=jow', 'Salade lentilles feta
Italian lentil salad : https://app.jow.com/EC0U?action=recipe&recipeId=5ede1926e86756246cded5f3&source=jow', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('e61ddffa-1956-52c7-a7ec-153ba4540911', 'Salade nectarines rôties, feta, roquette', null, null, null, array['salade','à compléter']::text[], '{}'::text[], '{}'::text[], 'Titre du lien : « Recette salade nectarines rôties et feta - Mon Marché ».
Import Notion — ambigu : Seulement un lien, pas de contenu.', 'https://www.mon-marche.fr/recette/la-salade-de-nectarines-roties-feta-et-roquette', 'Salade nectarine rôti fêta roquette
Recette salade nectarines rôties et feta - Mon Marché : https://www.mon-marche.fr/recette/la-salade-de-nectarines-roties-feta-et-roquette', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('c3a2780e-8346-510d-a4e0-b0c0eb07ac86', 'Salade courgettes nectarine', null, null, null, array['salade','à compléter']::text[], '{}'::text[], '{}'::text[], 'Titre du lien : « Nectarine & Zucchini Salad ».
Import Notion — ambigu : Seulement un lien (Jow), pas de contenu.', 'https://app.jow.com/EC0U?action=recipe&recipeId=5b6062bc0e95e00014536fcc&source=jow', 'Salade courgettes nectarine
Nectarine & Zucchini Salad : https://app.jow.com/EC0U?action=recipe&recipeId=5b6062bc0e95e00014536fcc&source=jow', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('f16d9feb-2236-5d61-a8da-bbefaf45a81c', 'Bucatini bisque de homard & gambas', 4, null, null, array['pâtes','fruits de mer','gambas']::text[], array['{"qty":400,"unit":"g","name":"bucatini","note":null}'::jsonb,'{"qty":400,"unit":"g","name":"bisque de homard","note":null}'::jsonb,'{"qty":10,"unit":"cl","name":"cognac","note":null}'::jsonb,'{"qty":20,"unit":null,"name":"gambas","note":null}'::jsonb,'{"qty":1,"unit":null,"name":"échalote","note":null}'::jsonb,'{"qty":1,"unit":null,"name":"oignon","note":null}'::jsonb,'{"qty":3,"unit":"gousse","name":"ail","note":null}'::jsonb,'{"qty":15,"unit":"cl","name":"vin blanc sec","note":null}'::jsonb,'{"qty":400,"unit":"g","name":"coulis de tomates","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"persil plat","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"huile d''olive","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"sel","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"poivre","note":null}'::jsonb]::text[], array['Dans une casserole faites chauffer un filet d''huile d''olive. Ajoutez l''oignon, le céleri, l''ail et l''échalote, faites-les revenir 4 à 5 minutes.','Ajoutez le cognac et le vin blanc, faites bouillir 2 minutes. Ajoutez la sauce tomate et la bisque de homard. Salez, poivrez. Portez à ébullition, baissez le feu et laissez mijoter à découvert 40 minutes.','Faites cuire les pâtes, al dente, dans un grand volume d''eau salée.','Pendant ce temps, faites chauffer un filet d''huile dans une poêle. Faites sauter les gambas 1 minute à feu vif. Salez, poivrez. Ajoutez l''ail et un peu de persil. Poursuivez la cuisson une petite minute.','Égouttez les pâtes, ajoutez la sauce et les gambas, parsemez de persil haché. C''est prêt.']::text[], 'L''étape 1 mentionne du céleri, qui n''apparaît pas dans la liste d''ingrédients d''origine.', 'https://kuri.app/NiB8Rh5c2Qb', null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('46e3ac21-d47e-5709-a974-3e849b370866', 'Penne au saumon', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ Penne au saumon', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('6054df4d-ec70-5dd9-a942-29373c2bc79f', 'Risotto de coquillettes au jambon', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ risotto de coquillettes au jambon', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('0a563e51-7a3c-5100-af8c-142fcd7b5c1e', 'Porc au caramel', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ porc au caramel', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('dde63e60-40b2-5b9c-a307-aba028a86d14', 'Aubergines asiatiques', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ aubergines asiatiques', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('5b4b7159-cf32-5ec3-ac7e-133917b142c7', 'Couscous', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ couscous', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('2733b2c7-d096-5886-afa1-9e6c1c9f69b6', 'Rougail saucisse', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ rougail saucisse', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('39299c51-b5e0-5ee9-aff2-3034e14ef6e7', 'Poulet au curry Martini', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre (marqué 🖍️ dans Notion : à écrire).', null, '🖍️ poulet au curry Martini', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('a7212d7c-c7e8-59b4-a1ad-e7b68aed0e4c', 'Côtes de porc / Choï Sum', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Import Notion — ambigu : Seulement un titre et un lien (marqué 🖍️ dans Notion).', 'https://www.peko-peko.fr/recettes/baizhuo-caixin/', '🖍️ Côtes de porc/Choï Sum
https://www.peko-peko.fr/recettes/baizhuo-caixin/', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('97c1adfb-9a12-5726-a036-be899e7daa5b', 'Poêlée d''igname aux lardons', null, null, null, array['à compléter']::text[], '{}'::text[], '{}'::text[], 'Titre du lien : « Recette Igname poêlé aux lardons - Grand Frais ».
Import Notion — ambigu : Seulement un titre et un lien (marqué 🖍️ dans Notion).', 'https://www.grandfrais.com/recettes/igname-poele-aux-lardons', '🖍️ Poêlée d''igname lardons
Recette Igname poêlé aux lardons - Grand Frais : https://www.grandfrais.com/recettes/igname-poele-aux-lardons', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z')
on conflict (id) do nothing;

insert into public.techniques (id, title, description, steps, pitfalls, tags, photo_url, is_example, created_by, created_at, updated_at) values
  ('4424d6d6-633e-535b-a70f-43ea7885c15b', 'Ciseler un oignon', 'Couper un oignon en petits dés réguliers, rapidement et sans larmes (ou presque). Sert de base à la plupart des plats mijotés et des sauces.', array['Couper l''oignon en deux par la racine, éplucher chaque moitié en gardant la racine : c''est elle qui tient les couches ensemble.','Poser la moitié à plat. Faire des incisions horizontales vers la racine sans la traverser.','Faire des incisions verticales, parallèles, de la pointe vers la racine, toujours sans la traverser.','Trancher perpendiculairement : les dés tombent tout seuls. Jeter la racine.']::text[], array['Couper la racine dès le début : l''oignon se défait et les dés sont irréguliers.','Un couteau mal affûté écrase les cellules et fait pleurer davantage.']::text[], array['découpe','base']::text[], null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('b59d78ba-03c3-55bf-aaeb-561a1ad9c259', 'Cuire des pâtes al dente', 'Des pâtes fermes sous la dent, qui finissent de cuire dans la sauce. Utile pour [[Spaghetti alle vongole]] et [[Pâtes au poulet & tomates cerises]].', array['Un grand volume d''eau (environ 1 litre pour 100 g de pâtes), porté à forte ébullition.','Saler franchement à l''ébullition (environ 10 g par litre) : c''est la seule occasion d''assaisonner les pâtes elles-mêmes.','Verser les pâtes, remuer dans la première minute pour qu''elles ne collent pas.','Goûter 1 à 2 minutes avant le temps indiqué sur le paquet : la pâte doit résister un peu au centre.','Prélever une louche d''eau de cuisson avant d''égoutter, puis finir la cuisson 1 à 2 minutes dans la sauce avec un peu de cette eau.']::text[], array['Rincer les pâtes : cela enlève l''amidon qui lie la sauce.','Mettre de l''huile dans l''eau : inutile, et la sauce accroche moins.','Égoutter à fond sans garder d''eau de cuisson : la sauce sera sèche.']::text[], array['cuisson','pâtes','base']::text[], null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('ceeb5dcb-b432-50e9-a56b-b67420885776', 'Déglacer', 'Récupérer les sucs caramélisés au fond d''une poêle ou d''une casserole avec un liquide (vin, alcool, bouillon, eau) pour en faire la base d''une sauce. C''est ce que fait l''étape au cognac et vin blanc de [[Bucatini bisque de homard & gambas]].', array['Après avoir saisi viande, crustacés ou aromates, retirer l''excès de gras mais garder les sucs bruns au fond.','Verser le liquide (2 à 10 cl) sur feu vif : il bout immédiatement.','Gratter le fond avec une spatule en bois pour décoller tous les sucs.','Laisser réduire de moitié avant d''ajouter le reste de la sauce.']::text[], array['Déglacer une poêle brûlée (sucs noirs) : la sauce sera amère.','Utiliser un vin qu''on ne boirait pas : son défaut se concentre en réduisant.']::text[], array['sauce','base']::text[], null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('77e3b5b7-c796-5f32-a3e2-56058499f165', 'Faire dégorger des coquillages', 'Débarrasser palourdes, coques ou moules de leur sable avant cuisson. Indispensable pour [[Spaghetti alle vongole]].', array['Rincer les coquillages à l''eau froide et jeter ceux qui sont cassés ou qui restent ouverts quand on les tapote.','Les mettre dans un saladier d''eau froide salée (environ 30 g de sel par litre, comme la mer).','Laisser reposer 20 à 30 minutes au frais : ils recrachent leur sable.','Sortir les coquillages à la main (ne pas verser le saladier : le sable retomberait dessus), changer l''eau et recommencer une ou deux fois.','Rincer une dernière fois et égoutter.']::text[], array['Eau non salée : les coquillages se referment et ne dégorgent pas.','Trop longtemps dans l''eau (plus d''une heure) : ils s''épuisent et meurent.']::text[], array['préparation','fruits de mer']::text[], null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('d6dbfc47-bcd7-540e-a10f-5a7abacf900e', 'Roux et béchamel', 'Le roux (beurre + farine cuits ensemble) épaissit les sauces. Mouillé au lait, il devient béchamel ; au bouillon, velouté.', array['Fondre 40 g de beurre à feu doux, ajouter 40 g de farine et cuire 2 minutes en remuant : le mélange mousse et sent le biscuit (roux blanc).','Verser 50 cl de lait froid d''un coup, fouetter énergiquement pour éviter les grumeaux.','Porter à frémissement en remuant sans arrêt jusqu''à épaississement (3 à 5 minutes).','Assaisonner : sel, poivre, muscade.']::text[], array['Lait chaud sur roux chaud : grumeaux garantis. L''un des deux doit être froid.','Arrêter de remuer : ça attache et brûle au fond.']::text[], array['sauce','base']::text[], null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z')
on conflict (id) do nothing;

insert into public.drinks (id, kind, name, type, region, vintage, notes, stock, peak_from, peak_to, drink_before, is_shot, ingredients, method, photo_url, is_example, created_by, created_at, updated_at) values
  ('549e70c3-8a4b-5540-a80b-0aa61c3c69de', 'wine', 'Irancy Fontaine Goby', null, 'Irancy', 2019, null, 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('feab82e5-b9af-590c-a468-51f95455858a', 'wine', 'Sciaccarellu « Sempre Contentu » – Domaine Giacometti', 'sciaccarellu', null, 2021, null, 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('cb9211d6-155d-5c52-abfa-482f6a8141d3', 'wine', 'Vosne-Romanée', null, 'Vosne-Romanée', null, 'Goûté chez Meiji.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('fff7390e-a9ac-521a-a280-7035f44ab60b', 'wine', 'Prunelart doux', 'doux', null, 2020, 'Goûté chez Meiji.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('4cc5949d-e916-502a-af29-cbc9c70f9cf3', 'wine', 'Fumey-Chatelain Arbois', null, 'Arbois', 2017, 'Goûté au Vaisseau (Cachot).', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('ca68459d-c1c0-51c0-a45c-730595f4d877', 'wine', 'Inopia rouge – Rotem et Mounir', 'rouge', null, 2018, 'Goûté au Vaisseau (Cachot).', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('1aac912a-5bba-58fe-ada0-dabc72303ddf', 'spirit', 'Hampden Estate 8 ans', 'rhum', null, null, 'Goûté au Vaisseau (Cachot).', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('5ae0fdea-e141-5ae6-ad41-6e7fe69553e0', 'wine', 'L''Arjolle Paradoxe', null, null, null, 'Le Bouclier de Bacchus.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('3ea3d444-cee2-5fcf-a4b3-569b5f085eed', 'wine', 'Domaine de Vénus – L''Effrontée', null, null, null, 'Le Bouclier de Bacchus.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('72f74ba8-417a-5b2c-aa55-31290441688a', 'wine', 'Le Versant – Loulou et Caroline', null, null, 2021, 'Le Bouclier de Bacchus.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('7cae6808-663d-5821-abb0-4ca764f8cd0a', 'wine', 'Domaine de Nigri', null, null, null, 'Noté sous « Macron » dans Notion.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('e87e8069-4839-58fb-aa0d-f944dda77083', 'wine', 'Domaine Pélaquié', null, null, null, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('43d44224-e846-5681-a1ea-408375e20cd7', 'wine', 'Cuvée Amandine – Saint-Joseph', null, 'Saint-Joseph', 2024, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('695c9fe9-c5c7-5ddd-a075-dab1038c1d6d', 'wine', 'Château du Moulin-à-Vent – La Rochelle', null, 'Moulin-à-Vent', 2023, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('83e2102e-e805-5300-a506-af2b8af0d269', 'wine', 'Domaine Faiveley – Mercurey Vieilles Vignes', null, 'Mercurey', 2023, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('dc82cde4-eb51-51ae-a4e3-e16f8ad912ee', 'wine', 'Château Mont-Redon – Châteauneuf-du-Pape', null, 'Châteauneuf-du-Pape', 2015, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('48467fc4-3a43-5c09-a029-50812e7e05f2', 'wine', 'Château Bélair-Monange – Premier Grand Cru Classé Saint-Émilion', null, 'Saint-Émilion', 2019, 'Grand Tasting Louvre.', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('e3594eb9-76ff-52d9-aaeb-3eda608c3b3e', 'cocktail', 'Entier', null, null, null, 'Dosages non notés dans Notion.', 0, null, null, null, true, array['{"qty":null,"unit":null,"name":"Chartreuse jaune","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"Aperol","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"mezcal","note":null}'::jsonb]::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('3983a2a1-b37e-51ef-a076-817551a8fc7f', 'cocktail', 'Perchoir Ménilmontant', null, null, null, 'Dosages non notés dans Notion.', 0, null, null, null, true, array['{"qty":null,"unit":null,"name":"mezcal","note":"Vida"}'::jsonb,'{"qty":null,"unit":null,"name":"sirop de piment maison","note":null}'::jsonb]::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('cfa9c863-e544-5871-adc0-67962ba12739', 'cocktail', 'Mini Guinness', null, null, null, 'Aucun détail dans Notion.', 0, null, null, null, true, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('869d5f3b-d29f-57be-a576-25d9febfa3d0', 'cocktail', 'Spritz PSG', null, null, null, 'Dans Notion, seulement une photo (non importée).', 0, null, null, null, false, '{}'::text[], null, null, false, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('9778670a-aaaa-5e24-aaff-42e2e8d420fd', 'wine', 'Chinon rouge (exemple)', 'rouge', 'Loire', 2020, 'Fiche d''exemple : montre la gestion de cave (stock, apogée, « à boire avant »). À adapter ou supprimer.', 2, 2024, 2030, '2031-12-31', false, '{}'::text[], null, null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('895dc21f-7865-5ecf-ab23-4266ff6d2df3', 'spirit', 'Gin London Dry (exemple)', 'gin', null, null, 'Fiche d''exemple. En stock, donc compté automatiquement dans « Mon bar ».', 1, null, null, null, false, '{}'::text[], null, null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('cd1c5c38-d496-581b-adb6-13e5d4b3d153', 'spirit', 'Campari (exemple)', 'bitter', null, null, 'Fiche d''exemple. En stock, donc compté automatiquement dans « Mon bar ».', 1, null, null, null, false, '{}'::text[], null, null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('1b975f5c-3386-5418-a071-51f42aa2cb08', 'cocktail', 'Negroni', null, null, null, 'Fiche d''exemple (dosages classiques). Avec le gin et le Campari d''exemple en cave, il ne manque que le vermouth : c''est le cas « à un ingrédient près ».', 0, null, null, null, false, array['{"qty":3,"unit":"cl","name":"gin","note":null}'::jsonb,'{"qty":3,"unit":"cl","name":"Campari","note":null}'::jsonb,'{"qty":3,"unit":"cl","name":"vermouth rouge","note":null}'::jsonb]::text[], 'Dans un verre old fashioned rempli de glaçons, verser les trois ingrédients et remuer à la cuillère 20 secondes. Garnir d''un zeste d''orange.', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('6e0f1945-fbaa-5a58-ac81-7b3af6fca4c0', 'cocktail', 'Mojito', null, null, null, 'Fiche d''exemple (dosages classiques).', 0, null, null, null, false, array['{"qty":5,"unit":"cl","name":"rhum blanc","note":null}'::jsonb,'{"qty":3,"unit":"cl","name":"jus de citron vert","note":null}'::jsonb,'{"qty":2,"unit":"c. à café","name":"sucre de canne","note":null}'::jsonb,'{"qty":6,"unit":"feuille","name":"menthe","note":null}'::jsonb,'{"qty":null,"unit":null,"name":"eau gazeuse","note":"pour compléter"}'::jsonb]::text[], 'Piler doucement la menthe avec le sucre et le citron vert dans un verre highball, ajouter le rhum, remplir de glace pilée, compléter d''eau gazeuse et remuer.', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z'),
  ('119833aa-3f80-5321-a657-43675aaf359f', 'cocktail', 'Spritz', null, null, null, 'Fiche d''exemple (dosages classiques). À comparer avec [[Spritz PSG]].', 0, null, null, null, false, array['{"qty":6,"unit":"cl","name":"prosecco","note":null}'::jsonb,'{"qty":4,"unit":"cl","name":"Aperol","note":null}'::jsonb,'{"qty":2,"unit":"cl","name":"eau gazeuse","note":null}'::jsonb]::text[], 'Dans un grand verre à vin rempli de glaçons : prosecco, puis Aperol, puis eau gazeuse. Une tranche d''orange.', null, true, null, '2026-09-27T09:00:00Z', '2026-09-27T09:00:00Z')
on conflict (id) do nothing;

insert into public.pantry_items (id, name, created_at) values
  ('a322e893-4a9a-5182-a1f6-7633885679e9', 'sel', '2026-09-27T09:00:00Z'),
  ('a6479e63-137c-5029-a5f2-11d51edd44ef', 'poivre', '2026-09-27T09:00:00Z'),
  ('ac4ed587-9811-5cac-aa93-42702f5a9e16', 'huile d''olive', '2026-09-27T09:00:00Z'),
  ('a674209f-e749-519e-a405-d3860a46ef88', 'huile', '2026-09-27T09:00:00Z'),
  ('ba8e1ac2-5508-5510-a198-ac0587e038ef', 'farine', '2026-09-27T09:00:00Z'),
  ('74dbf6ce-1fdc-5801-abb1-b4078c15eb2d', 'sucre', '2026-09-27T09:00:00Z'),
  ('60e5cacc-502d-59de-a52a-93665a1e9c4d', 'beurre', '2026-09-27T09:00:00Z'),
  ('47fb4a2b-a326-539f-aae8-ef5701a68df4', 'vinaigre', '2026-09-27T09:00:00Z'),
  ('28c9e8c5-3e8c-57bf-ae0e-d21806116d18', 'origan', '2026-09-27T09:00:00Z'),
  ('5452ef48-3e8f-54e9-aec0-052ca8e3c834', 'thym', '2026-09-27T09:00:00Z'),
  ('bfa1ef8e-7c72-5f47-ae63-cfacd526869b', 'paprika', '2026-09-27T09:00:00Z'),
  ('8875f9dd-01a7-5821-ac40-cf12838acb59', 'cumin', '2026-09-27T09:00:00Z'),
  ('10dd97a2-45e6-5a24-abcf-f3a1f9f6ab78', 'maïzena', '2026-09-27T09:00:00Z'),
  ('7b985d2f-a76c-5692-a9c1-771457e3b146', 'eau', '2026-09-27T09:00:00Z')
on conflict (id) do nothing;
